# Generated by Django 5.2.7 on 2025-12-18 09:54

import django.contrib.auth.models
from django.db import migrations, models


def set_username_to_email(apps, schema_editor):
    CustomUser = apps.get_model('auth_app', 'CustomUser')
    for user in CustomUser.objects.all():
        user.username = user.email
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RunPython(set_username_to_email, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
