# Generated by assistant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(upload_to='thumbnails/', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
    ]
