# Generated by Django 5.2.7 on 2026-01-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_add_thumbnail_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='conversion_status',
            field=models.CharField(blank=True, default='pending', max_length=20, null=True),
        ),
    ]
