# Generated by Django 5.2.7 on 2026-01-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_video_conversion_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
    ]
